configuration: Release

# Restore NuGet packages before running MSBuild
before_build:
  - nuget restore .\src\Sitecore.Azure.Diagnostics.sln

# Automatically register private account AppVeyor NuGet feeds.
nuget:
  account_feed: true